using RMS.Infrastructure.IRepositories;
using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RMS.Application.DTOs;
using RMS.Domain.Interfaces;
using RMS.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RMS.Application.Interfaces;

namespace RMS.Application.Implementations
{
    public class PayrollService : IPayrollService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ITenantService _tenantService;
        private readonly IMapper _mapper;
        private readonly ILogger<PayrollService> _logger;

        public PayrollService(IUnitOfWork unitOfWork, ITenantService tenantService, IMapper mapper, ILogger<PayrollService> logger)
        {
            _unitOfWork = unitOfWork;
            _tenantService = tenantService;
            _mapper = mapper;
            _logger = logger;
        }

        public async Task<ResponseDto<List<PayrollDto>>> GetAllPayrollsAsync()
        {
            var payrolls = await _unitOfWork.GetRepository<Payroll>().GetQueryable()
                .Include(p => p.Staff)
                .OrderByDescending(p => p.PayDate)
                .ToListAsync();

            return ResponseDto<List<PayrollDto>>.CreateSuccessResponse(_mapper.Map<List<PayrollDto>>(payrolls));
        }

        public async Task<ResponseDto<PayrollDto>> RunPayrollAiAsync(CreatePayrollDto runDto)
        {
            await _unitOfWork.BeginTransactionAsync();
            try
            {
                var staff = await _unitOfWork.GetRepository<Staff>().GetByIdAsync(runDto.StaffID);
                if (staff == null) return ResponseDto<PayrollDto>.CreateErrorResponse("Staff not found.");

                // 1. Calculate Base Pay (Simulated hours for demo, in production link to Clock-In system)
                decimal basePay = staff.HourlyRate * 40; // Assume 40 hour week for AI simulation

                // 2. AI Commission Analysis (Heuristic)
                // Analyze revenue generated by this staff member in the given period
                var revenueGenerated = await _unitOfWork.GetRepository<Order>().GetQueryable()
                    .Where(o => o.StaffID == staff.StaffID && o.OrderStatus == "Paid" 
                             && o.CreatedDate >= runDto.PeriodStart && o.CreatedDate <= runDto.PeriodEnd)
                    .SumAsync(o => o.Total);

                decimal commission = revenueGenerated * (staff.CommissionPercentage / 100);

                var payroll = new Payroll
                {
                    StaffID = staff.StaffID,
                    PayDate = DateTime.UtcNow,
                    PeriodStart = runDto.PeriodStart,
                    PeriodEnd = runDto.PeriodEnd,
                    BasePay = basePay,
                    CommissionEarned = commission,
                    BonusAmount = runDto.BonusAmount,
                    BranchID = staff.BranchID,
                    CreatedBy = "AI_PAYROLL_BOT",
                    CreatedDate = DateTime.UtcNow
                };

                var newPayroll = await _unitOfWork.GetRepository<Payroll>().AddAsync(payroll);
                await _unitOfWork.SaveChangesAsync();
                await _unitOfWork.CommitTransactionAsync();

                return ResponseDto<PayrollDto>.CreateSuccessResponse(_mapper.Map<PayrollDto>(newPayroll), "Payroll generated by AI analysis.");
            }
            catch (Exception ex)
            {
                await _unitOfWork.RollbackTransactionAsync();
                _logger.LogError(ex, "Payroll generation failed.");
                return ResponseDto<PayrollDto>.CreateErrorResponse(ex.Message);
            }
        }
    }
}
